model_name: "Davidozito/xlm-roberta-danish-educational-scorer-zeroshot"
num_labels: 1  # Regression head

model_dir: "models"
val_split: 0.1
num_train_epochs: 5
per_device_train_batch_size: 16
per_device_eval_batch_size: 32
eval_steps: 50
evaluation_strategy: "steps"
logging_strategy: "steps"
save_strategy: "steps"
learning_rate: 3e-4

# Danish/English data selection for merging
num_danish_samples: 0      # Number of Danish samples to include
num_english_samples: 0       # Number of English samples to include
